volumes:
  gosrc:

services:
  social-network:
    build:
      context: .
      dockerfile: Dockerfile
    image: van4ik/social-net:1.0.4
    environment:
      - DB_MASTER=postgres://social:social@pgmaster:5432/social
      - DB_SLAVE1=postgres://social:social@pgslave1:5432/social
      - DB_SLAVE2=postgres://social:social@pgslave2:5432/social
      - REDIS_CONNECTION=redis:6379
      - SERVER_PORT=80
    volumes:
      - ./app:/app
      - gosrc:/go
    networks:
      - app-network
    depends_on:
      pgmaster:
        condition: service_healthy
    restart: unless-stopped